id: P946F5AA5
initial_creation_type: input
source_metadata:
  Title: Vādanyāya of Dharmakirti
  Editor: Gokhale, P. P.
  Publisher: Sri Satguru Publications
  Place of Publication: India
  Year: '1993'
  Vādanyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:51:19.185955'
last_modified_at: '2022-03-08T16:51:19.185963'
